using Cardevil.Cards.Evaluations;
using Cardevil.Core.Bootstrap;
using Cardevil.Core.Turn;
using Cardevil.Core.Turn.Interfaces;
using Cardevil.DebugConsole;
using Cardevil.Events.AsyncPriorityEvent;
using Cardevil.Events.Core;
using Cardevil.Ingame.Entities;
using Cardevil.Ingame.Field;
using Cardevil.Utils;
using Cardevil.Utils.Directions;
using Cysharp.Threading.Tasks;
using DG.Tweening;
using JetBrains.Annotations;
using System;
using UnityEngine;
using UnityEngine.Scripting;
using UnityEngine.Serialization;
using Console = Cardevil.DebugConsole.Console;

namespace Cardevil.Ingame.Player
{
    /// <summary>
    /// н”Ңл Ҳмқҙм–ҙ мәҗлҰӯн„° нҒҙлһҳмҠӨ
    /// </summary>
    public class PlayerCharacter : MonoBehaviour, IPlayerControl, ITurnPlayer
    {
        [Header("Debug")]
        [SerializeField] protected bool _isDebugMode = false;
        [SerializeField] protected bool _initTileManually = false;
        [SerializeField] protected Tile _initialTile;
        [Header("Settings")] 
        [SerializeField] protected PlayerCharacterSettingSO playerCharacterSetting;
        [Header("References")]
        [SerializeField] protected Entity _entity;
        [SerializeField] protected PlayerVisual _playerVisual;


        public float MoveSpeed => playerCharacterSetting.moveSpeed;
        private void Reset()
        {
            _entity = GetComponent<Entity>();
            _playerVisual = GetComponentInChildren<PlayerVisual>(); 
        }

        public Entity Entity => _entity;
        public Field.Field Field { get; private set; }
        public PlayerStatus PlayerStatus => Bootstrapper.Instance.Game.PlayerStatus;
        public PlayerVisual PlayerVisual => _playerVisual;
        private void Awake()
        {
            if(_entity == null)
            {
                _entity = GetComponent<Entity>();
            }
        }
        
        private void Start()
        {
            if (_initTileManually)
            {
                if (_initialTile == null)
                {
                    LogEx.LogError("Initial tile is not set. Please assign a tile in the inspector.");
                    return;
                }
                _entity.Init(_initialTile);
                // Bootstrapper.Instance.Game.Player = this; // кІҢмһ„ л§ӨлӢҲм Җм—җ н”Ңл Ҳмқҙм–ҙ м„Өм •
            }
        }

        public void Init(Field.Field field)
        {
            Field = field;
            
            if(_entity == null)
            {
                _entity = GetComponent<Entity>();
            }
            
            if (_initTileManually)
            {
                if (_initialTile == null)
                {
                    LogEx.LogError("Initial tile is not set. Please assign a tile in the inspector.");
                    return;
                }
                _entity.Init(_initialTile);
                // Bootstrapper.Instance.Game.Player = this; // кІҢмһ„ л§ӨлӢҲм Җм—җ н”Ңл Ҳмқҙм–ҙ м„Өм •
            }
        }

        public void Update()
        {
            if (_isDebugMode)
            {
                if(Input.anyKeyDown)
                {
                    int horizontal = (int)Input.GetAxisRaw("Horizontal");
                    int vertical = (int)Input.GetAxisRaw("Vertical");
                    // print($"Horizontal: {horizontal}, Vertical: {vertical}");
                    if (horizontal != 0 || vertical != 0)
                    {
                        Direction direction = Direction.None;
                        if (horizontal > 0) direction = Direction.Right;
                        else if (horizontal < 0) direction = Direction.Left;
                        else if (vertical > 0) direction = Direction.Up;
                        else if (vertical < 0) direction = Direction.Down;
                        LogEx.Log($"Moving in direction: {direction}");
                        MoveWithAnim(direction);
                    }
                }
            }
        }

        /*
         * IPlayerControl мқён„°нҺҳмқҙмҠӨ кө¬нҳ„
         * TODO : Move л©”м„ңл“ң к°ңм„ . нҳ„мһ¬лҠ” мҰүмӢңмқҙлҸҷ + wrapAround нҷңм„ұнҷ”
         * 
         */


        /// <summary>
        /// н”Ңл Ҳмқҙм–ҙлҘј н•ҙлӢ№ л°©н–ҘмңјлЎң н•ң м№ё мқҙлҸҷмӢңнӮөлӢҲлӢӨ.
        /// </summary>
        /// <remarks>
        /// transformмқҖ л°”лЎң мқҙлҸҷн•ҳм§Җ м•Ҡкі , м• лӢҲл©”мқҙм…ҳмқ„ нҶөн•ҙ мқҙлҸҷн•©лӢҲлӢӨ.
        /// </remarks>
        /// <param name="direction"></param>
        public async UniTask MoveWithAnim(Direction direction)
        {
            await MoveWithAnim(direction, 1);
        }

        /// <summary>
        /// н”Ңл Ҳмқҙм–ҙлҘј н•ҙлӢ№ л°©н–ҘмңјлЎң distance м№ё мқҙлҸҷмӢңнӮөлӢҲлӢӨ.
        /// </summary>
        /// <remarks>
        /// transformмқҖ л°”лЎң мқҙлҸҷн•ҳм§Җ м•Ҡкі , м• лӢҲл©”мқҙм…ҳмқ„ нҶөн•ҙ мқҙлҸҷн•©лӢҲлӢӨ.
        /// </remarks>
        /// <param name="direction"></param>
        /// <param name="distance"></param>
        public async UniTask MoveWithAnim(Direction direction, int distance)
        {
            /*
             * 1. мқҙлҸҷн•  мң„м№ҳлҘј л°ӣм•„мҳЁлӢӨ.
             * 2. Wrapмқҙ м•„лӢҲлқјл©ҙ, нҸүлІ”н•ҳкІҢ мқҙлҸҷ
             * 3. Wrapмқҙлқјл©ҙ, нҠ№мҲҳ м• лӢҲл©”мқҙм…ҳ
             *
             * A. мӣҗлһҳ к°Җл Өкі  н–ҲлҚҳ мң„м№ҳ л°ӣм•„мҳӨкё°
             * 
             */
            bool wrapped = false;
            Tile targetTile = Field.GetTileByDirectionWrap(_entity.CurrentTile, direction, out wrapped, distance);
            Tile originalTile = _entity.CurrentTile;
            _entity.MoveTo(targetTile, false);
            
            async UniTask MoveTask(Vector3 endPosition)
            {
                PlayerVisual.MoveDirection = direction.ToTileVector().ToVector2IntDirect();
                PlayerVisual.IsRunning = true;
                var tween = transform.DOMove(endPosition, 1f / MoveSpeed).SetEase(Ease.Linear);
                await tween.ToUniTask();
                PlayerVisual.IsRunning = false;
            }

            if (!wrapped)
            {
                Vector3 startPosition = transform.position;
                Vector3 targetPosition = _entity.CurrentTile.transform.position;
                targetPosition.y = startPosition.y; // Y м¶•мқҖ мң м§Җ
                await MoveTask(targetPosition);
            }
            else
            {
                Vector3 startPosition = transform.position;
                // м—¬лҹ¬м№ё мқҙлҸҷн–ҲлҚ”лқјлҸ„ н•ңм№ёл§Ң мқҙлҸҷн•ң кІғмңјлЎң м·Ёкёү
                Vector3 outPosition = Field.GetTileCenterWorld(originalTile.Coordinate + direction.ToTileVector());
                Vector3 targetPosition = _entity.CurrentTile.transform.position;
                outPosition.y = targetPosition.y = startPosition.y; // Y м¶•мқҖ мң м§Җ
                await MoveTask(outPosition);
                PlayerVisual.IsFalling = true;

                
                await transform.DOShakePosition(playerCharacterSetting.coyoteTime,
                    strength:playerCharacterSetting.coyoteShakeStrength * new Vector3(1,0,1),
                    vibrato:playerCharacterSetting.coyoteShakeCount,
                    randomness:90,
                    snapping:false,
                    fadeOut:true).ToUniTask();
                await UniTask.Delay(playerCharacterSetting.fallDelayAfterCoyoteTimeMs);
                
                var sequence = DOTween.Sequence();
                // л–Ём–ҙм§ҖлҠ” мӢңнҖҖмҠӨ
                sequence.Append(transform.DOMoveY(startPosition.y - playerCharacterSetting.fallHeight,
                    playerCharacterSetting.fallDuration).SetEase(playerCharacterSetting.fallEase));
                // л–Ём–ҙм§ҖлҠ” нҺҳмқҙл“ңм•„мӣғ
                float fadeoutStartTime = Mathf.Lerp(0, playerCharacterSetting.fallDuration,
                    playerCharacterSetting.fallFadeStartRatio);
                sequence.Insert(fadeoutStartTime,
                    DOTween.To(() => PlayerVisual.FadeAlpha, value => PlayerVisual.FadeAlpha = value,0, playerCharacterSetting.fallDuration-fadeoutStartTime));
                
               
                // лӢӨмӢң л–Ём–ҙм§ҖлҠ” мӢңнҖҖмҠӨ
                sequence.AppendCallback(() => transform.position = targetPosition + Vector3.up * playerCharacterSetting.fallHeight);
                sequence.Append(transform.DOMoveY(targetPosition.y,
                    playerCharacterSetting.fallDuration).SetEase(playerCharacterSetting.fallEase));
                float fadeinEndTime = Mathf.Lerp(0, playerCharacterSetting.fallDuration,
                    playerCharacterSetting.fallFadeEndRatio);
                sequence.Join(DOTween.To(() => PlayerVisual.FadeAlpha, value => PlayerVisual.FadeAlpha = value,1,fadeinEndTime));
                await sequence.ToUniTask();
                PlayerVisual.IsFalling = false;
            }
            
        }

        public void MoveTo(int i, int j)
        {
            _entity.MoveTo(new TileVector(i, j), true);
        }

        public void MoveTo(TileVector tileVector)
        {
            _entity.MoveTo(tileVector, true);
        }

        public void MoveTo(Tile tile)
        {
            if (tile == null)
            {
                LogEx.LogError("Cannot move to a null tile.");
                return;
            }
            _entity.MoveTo(tile, true);
        }
        /// <summary>  н”Ңл Ҳмқҙм–ҙмқҳ Horinzontal Line Number </summary>
        public int GetPlayerLineNumberHorizontal() 
        {
            return Entity.Tile.i;
        }
        /// <summary>  н”Ңл Ҳмқҙм–ҙмқҳ Vertical Line Number </summary>
        public int GetPlayerLineNumberVertical()
        {
            return Entity.Tile.j;
        }

        #region ITurnPlayerAction кө¬нҳ„
        
        public bool IsDead { get; }

        public async UniTask<AttackResult> TurnAttackAsync(IReadOnlyTurnContext ctx)
        {
            LogEx.Log("Player Attacks!");

            await UniTask.Delay(100);

            var result = ctx.CardFlow.Result;
            int damage = result.TotalDamage;
            var handRanking = result.HandRanking;

            LogEx.Log($"н”Ңл Ҳмқҙм–ҙ кіөкІ© : {damage} н”јн•ҙ. кө¬нҳ„ м•„м§Ғ");
            PlayerVisual.PlayAttackAnimation();
            // TODO: кіөкІ© м• лӢҲл©”мқҙм…ҳлҸ„ awaitн•ҳкё°
            
            return new AttackResult(target: ctx.CurrentEnemy, handRanking, damage);
        }
        
        public void TakeDamage(int amount)
        {
            LogEx.Log($"Player takes {amount} damage!");
            PlayerStatus.TakeDamage((int)amount);
        }

        public async UniTask<Vector2Int> TurnMove(IReadOnlyTurnContext ctx)
        {
            LogEx.Log("Player Moves!");
            var result = ctx.CardFlow.Result;
            //TODO мқҙлҸҷ лЎңм§Ғ кө¬нҳ„
            foreach (var move in result.Moves)
            {
                if (!move.DirectionSelectState.FinalValue.HasValue)
                    continue;
                
                await MoveWithAnim((Direction)move.DirectionSelectState.FinalValue, move.Length);
                await UniTask.Delay(300);
            }
            LogEx.Log("Player Move Completed!");

            return new Vector2Int(Entity.Tile.i, Entity.Tile.j);
        }

        #endregion



        [Preserve, ConsoleCommand("togglePlayerDebug", "Toggle player debug mode")]
        private static void TogglePlayerDebug()
        {
            var player = FindFirstObjectByType<PlayerCharacter>();
            if (player != null)
            {
                player._isDebugMode = !player._isDebugMode;
                Console.MessageInfo($"Player debug mode: {(player._isDebugMode ? "ON" : "OFF")}");
            }
            else
            {
                Console.MessageError("No PlayerCharacter found in the scene.");
            }
        }
    }
}